.mode csv
.headers on
.once 'S:\Supply_Chain\Analytics\Inventory Allocation Maximization\MVP Data\input tables\Transportation_Policies.csv'

select distinct mi.whs_code as Source
,'(ALL_Customers)' as 'Destination'
,'' as 'Ship To'
,'(ALL_Products)' as 'Product'
,'' as 'CollectionBasisProductName'
,'' as 'Mode'
,'' as 'Transportation Policy'
,'' as 'Policy Parameter'
,'' as 'Review Period'
,'' as 'Mode Function'
,'' as 'Shipment Period'
,'' as 'Replenishment Frequency'
,'' as 'Transport Time'
,'' as 'Distance'
,'' as 'Asset'
,'' as 'Variable Transportation Cost'
,'' as 'Variable Cost Basis'
,'' as 'Fixed Shipment Cost'
,'' as 'Shipment Size'
,'' as 'Shipment Rule'
,'' as 'Product Class'
,'' as 'Duty Rate'
,'' as 'Discount Rate'
,'' as 'Minimum Charge'
,'' as 'Fuel Surcharge'
,'' as 'Fuel Surcharge Basis'
,'' as 'CO2'
,'' as 'CO2 Basis'
,'' as 'Require Return Trip'
,'' as 'Return Trip Time'
,'' as 'Return Trip Cost'
,'' as 'Load Resource'
,'' as 'Unload Resource'
,'' as 'Auto-release Load Resource'
,'' as 'Auto-release Unload Resource'
,'' as 'Fixed Load Cost'
,'' as 'Unit Load Cost'
,'' as 'Fixed Load Time'
,'' as 'Unit Load Time'
,'' as 'Fixed Unload Cost'
,'' as 'Unit Unload Cost'
,'' as 'Fixed Unload Time'
,'' as 'Unit Unload Time'
,'' as 'Requirement Type'
,'' as 'Requirement Value'
,'' as 'Requirement Period'
,'' as 'Lane Consignment Queue Basis'
,'' as 'Mode Consignment Queue Basis'
,'' as 'Chance For Ambush'
,'' as 'Ambush Delay'
,'' as 'Ambush Damage'
,'' as 'Reorder When Destroyed'
,'' as 'Unit Delay Factor'
,'' as 'Delay Factor'
,'' as 'Minimum Replenishment Quantity'
,'' as 'Minimum Service Time'
,'' as 'Maximum Service Time'
,'' as 'Guaranteed Service Time'
,'' as 'Responsible Party'
,'' as 'Lane Name'
,'' as 'Path Name'
,'include' as 'Status'
,'' as 'Notes'
,'' as 'Load Schedule Rule'
,'' as 'Unload Schedule Rule'
,'' as 'Asset Departure Schedule Rule'
from mvp_inventory mi
;